### ISSUE TITLE
prefer-null-over-undefined: Allow undefined on ArgsType

### ISSUE THREAD

**Issue by AriFreyr** [borremosch/eslint-plugin-type-graphql#10]
Hello friends thanks for the plugin it has helped a lot.

I have a question/suggestion regarding `prefer-null-over-undefined`.

I am currently working with an `ArgsType` that has a nullable field, thing is `ArgsType` properties will both be delivered as `undefined` or `null` depending on how the client calls the server and both will have to be handled. This would mean that the following code should be valid but gives a `Prefer null over undefined in types that are exposed in the GraphQL schema`

```js
@ArgsType()
export class CoolArgsType {
  @Field(type => Int, { nullable: true })
  propertyInsideArgsType?: number | null
}
```

Any thoughts? I would think `InputTypes` behave the same way

**Comment by borremosch** [comment]
Thank you for your question @AriFreyr, it raises some very interesting points!

Since GraphQL is a query language that is agnostic to the programming language on both the server and client side, I had assumed that there is no place for `undefined` when communicating using GraphQL, and implemented the `prefer-null-over-undefined` rule accordingly. However, it does seem that there are two valid ways of not supplying an argument: by nulling it, or by not supplying it. In the JavaScript ecosystem this easily translates to something being `null` (when explicitly nulled), or `undefined` (when not supplied). Then again, this behavior is not part of the GraphQL specification because it aims to support many languages other than JavaScript, most of which do not support an `undefined` type.

Since this behavior is not part of the specification, the implementation may differ between GraphQL server implementations in JavaScript. In fact, behavior does not seem to be consistent even within implementations. For example, I have tested the example you supplied in my existing project that uses `apollo-server-express` and indeed, I was able to receive either `null` or `undefined` on the server end, depending on whether I supplied the property or not. However, when attempting the same for a query argument, the result was `undefined` in both cases! Worse still, the behavior of these implementations may change over time. This is not a hypothetical situation, as it has actually happened before in Apollo server (https://github.com/apollographql/react-apollo/issues/1569, https://github.com/apollographql/apollo-server/issues/2056). So while I believe there to be a valid semantic difference between `null` and `undefined`, I would strongly advice against relying on it on either receiving end of a connection using GraphQL.

So what does this mean for the linter? I believe the right course of action is to replace the current `prefer-null-over-undefined` rule with a `no-invalid-nullable-input-type` and a `no-invalid-nullable-output-type` rule. The input rule would enforce the input types to be defined as `Type | undefined | null`, since the input type can be either depending on the server implementation used. For the output type, I believe it to be best to restrict this to `null`, as it prevents accidental returning of `undefined`. Both rules should be configurable.

Let me know if you have any additional thoughs

**Comment by AriFreyr** [comment]
Thanks for the response! Great research and very interesting findings. I have been thinking about this and i came to the same conclusion, i think splitting it up is the best way to address this inconsistency. Experience has taught me when dealing with arguments/input and a JS server all bets are off regarding specs and docs :(
